### ISSUE TITLE
ApplicationID Filter not working

### ISSUE THREAD

**Issue by jamesbayly** [subquery/subql-algorand#23]
### Prerequisites

* [x] Are you running the latest version(s)?
* [x] Did you check the [debugging guide](https://doc.subquery.network/academy/tutorials_examples/debug-projects.html#how-to-debug-a-subquery-project)?
* [x] Did you check the [FAQs](https://doc.subquery.network/faqs/faqs.html) and [Discussions](https://github.com/subquery/subql/discussions)?
* [x] Are you reporting to the correct repository?
* [x] Did you search for an existing issue or pull request?

### Reproduction Steps

1. Init a fresh Algorand project
2. Update the manifest to the following 
```yaml
  - kind: algorand/Runtime
    startBlock: 25261956 # Note changed
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleTransaction
          kind: algorand/TransactionHandler
          filter:
            applicationId: 730196316 # Note changed
```
3. Log any input to `handleTransaction`

**Expected behavior:** The transaction at https://algoexplorer.io/tx/KCST4OMRLMJIBCR5WSCTD2ROCBYFB6TEU4LCKNJZ2D4QUTNLMURA should be indexed

**Actual behavior:** No transactions appear in `handleTransaction`
